name: superset
dependencies:
- libpq=9.5.4=0
- openssl=1.0.2j=0
- pip=9.0.1=py27_0
- psycopg2=2.6.2=py27_0
- python=2.7.12=1
- readline=6.2=2
- setuptools=27.2.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - alembic==0.9.6
  - amqp==2.2.2
  - anyjson==0.3.3
  - asn1crypto==0.24.0
  - babel==2.5.1
  - backports.ssl-match-hostname==3.5.0.1
  - billiard==3.5.0.3
  - boto3==1.5.9
  - botocore==1.8.23
  - celery==4.1.0
  - certifi==2017.11.5
  - cffi==1.11.2
  - chardet==3.0.4
  - click==6.7
  - colorama==0.3.9
  - cryptography==1.9
  - docutils==0.14
  - enum34==1.1.6
  - flask==0.12.2
  - flask-appbuilder==1.9.4
  - flask-babel==0.11.1
  - flask-cache==0.13.1
  - flask-login==0.2.11
  - flask-migrate==2.0.3
  - flask-openid==1.2.5
  - flask-script==2.0.5
  - flask-sqlalchemy==2.1
  - flask-testing==0.6.2
  - flask-wtf==0.14.2
  - flower==0.9.1
  - future==0.16.0
  - futures==3.2.0
  - gunicorn==19.7.1
  - humanize==0.5.1
  - idna==2.5
  - ipaddress==1.0.19
  - itsdangerous==0.24
  - jinja2==2.10
  - jmespath==0.9.3
  - kombu==4.1.0
  - mako==1.0.7
  - markdown==2.6.8
  - markupsafe==1.0
  - numpy==1.13.3
  - pandas==0.20.3
  - parsedatetime==2.0
  - pathlib2==2.3.0
  - pyasn1==0.1.9
  - pycparser==2.18
  - pydruid==0.3.1
  - pyhive==0.5.0
  - python-dateutil==2.6.0
  - python-editor==1.0.3
  - python-openid==2.2.5
  - pytz==2017.3
  - pyyaml==3.12
  - requests==2.17.3
  - s3transfer==0.1.12
  - sasl==0.2.1
  - scandir==1.6
  - simplejson==3.10.0
  - six==1.10.0
  - sqlalchemy==1.1.9
  - sqlalchemy-utils==0.32.16
  - sqlparse==0.2.3
  - superset==0.22.1
  - thrift==0.10.0
  - thrift-sasl==0.3.0
  - tornado==4.2
  - unidecode==1.0.22
  - urllib3==1.21.1
  - vine==1.1.4
  - werkzeug==0.14.1
  - wtforms==2.1
